version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    steps:
      - checkout
      - run:
          name: Update PIP
          command: pip install -U --user pip 

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "setup.py" }}
      #       - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[dev]
            pip install raiden==0.100.3

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          background: true
          name: Spin-up of Raiden node
          command: |
            . venv/bin/activate
            raiden --accept-disclaimer \
                   --keystore-path  ~/project/tests/fixtures/rinkeby/keystore \
                   --eth-rpc-endpoint "https://rinkeby.infura.io/v3/${INFURA_TOKEN}" \
                   --network-id rinkeby \
                   --environment-type development \
                   --address 0xe59a5927cbB5007ffF0384244354b158464C47d3 \
                   --password-file ~/project/tests/fixtures/rinkeby/password.txt
      - run:
          name: Waiting Raiden node to spin-up
          command: sleep 30s

      - run:
          name: run tests
          command: . venv/bin/activate && pytest tests/
