version: 2
jobs:
  unittests:
    docker:
      - image: circleci/python:3.7.3

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -e .[dev]

      - run:
          name: run tests
          command: pytest tests/endpoints/

  integration-tests:
    docker:
      - image: circleci/python:3.7.3

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -e .[dev]

      - run:
          background: true
          name: Spin-up of Raiden node
          command: raiden --accept-disclaimer \
                          --keystore-path  ~/project/tests/fixtures/rinkeby/keystore \
                          --eth-rpc-endpoint "https://rinkeby.infura.io/v3/${INFURA_TOKEN}" \
                          --network-id rinkeby \
                          --environment-type development \
                          --address 0xe59a5927cbB5007ffF0384244354b158464C47d3 \
                          --password-file ~/project/tests/fixtures/rinkeby/password.txt
      - run:
          name: Waiting Raiden node to spin-up
          command: sleep 30s
      - run:
          name: Run integration tests
          command: pytest --cov=./raiden_client && codecov --token=$CODECOV_TOKEN

  release-pypi:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --upgrade pip wheel setuptools twine
      - run:
          name: Build package
          command: python setup.py sdist bdist_wheel
      - run:
          name: Deploy pypi
          command: twine upload dist/* 

workflows:
  version: 2
  build:
    jobs:
      - unittests
      - integration-tests:
          filters:
            branches:
              only: master
      - pypi_release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integration-tests
            - unittests